-- ALTER diagnosis_master table to add icd_code column
ALTER TABLE diagnosis_master ADD COLUMN IF NOT EXISTS icd_code VARCHAR(20) NULL;

-- INSERT 100 diagnoses with ICD-10 codes
DELETE FROM diagnosis_master;
INSERT INTO diagnosis_master (diagnosis_name, icd_code, active) VALUES
('Hypertension',                                'I10',    true),
('Type 2 Diabetes Mellitus',                    'E11',    true),
('Type 1 Diabetes Mellitus',                    'E10',    true),
('Coronary Artery Disease',                     'I25.1',  true),
('Heart Failure',                               'I50',    true),
('Atrial Fibrillation',                         'I48',    true),
('Chronic Obstructive Pulmonary Disease',       'J44',    true),
('Asthma',                                      'J45',    true),
('Pneumonia',                                   'J18',    true),
('Chronic Kidney Disease',                      'N18',    true),
('Acute Kidney Injury',                         'N17',    true),
('Urinary Tract Infection',                     'N39.0',  true),
('Stroke',                                      'I63',    true),
('Transient Ischemic Attack',                   'G45.9',  true),
('Alzheimer Disease',                           'G30',    true),
('Dementia',                                    'F03',    true),
('Parkinson Disease',                           'G20',    true),
('Epilepsy',                                    'G40',    true),
('Multiple Sclerosis',                          'G35',    true),
('Peripheral Neuropathy',                       'G62.9',  true),
('Osteoarthritis',                              'M19.9',  true),
('Rheumatoid Arthritis',                        'M06.9',  true),
('Osteoporosis',                                'M81.0',  true),
('Gout',                                        'M10.9',  true),
('Anemia',                                      'D64.9',  true),
('Iron Deficiency Anemia',                      'D50.9',  true),
('Deep Vein Thrombosis',                        'I82.4',  true),
('Pulmonary Embolism',                          'I26.9',  true),
('Hypothyroidism',                              'E03.9',  true),
('Hyperthyroidism',                             'E05.9',  true),
('Gastroesophageal Reflux Disease',             'K21.0',  true),
('Peptic Ulcer Disease',                        'K27',    true),
('Irritable Bowel Syndrome',                    'K58.9',  true),
('Crohn Disease',                               'K50.9',  true),
('Ulcerative Colitis',                          'K51.9',  true),
('Liver Cirrhosis',                             'K74.6',  true),
('Non-Alcoholic Fatty Liver Disease',           'K76.0',  true),
('Cholecystitis',                               'K81.9',  true),
('Pancreatitis',                                'K85.9',  true),
('Appendicitis',                                'K37',    true),
('Breast Cancer',                               'C50.9',  true),
('Lung Cancer',                                 'C34.9',  true),
('Colorectal Cancer',                           'C20',    true),
('Prostate Cancer',                             'C61',    true),
('Cervical Cancer',                             'C53.9',  true),
('Ovarian Cancer',                              'C56.9',  true),
('Bladder Cancer',                              'C67.9',  true),
('Leukemia',                                    'C95.9',  true),
('Lymphoma',                                    'C85.9',  true),
('Skin Cancer - Melanoma',                      'C43.9',  true),
('Major Depressive Disorder',                   'F32.9',  true),
('Generalized Anxiety Disorder',                'F41.1',  true),
('Bipolar Disorder',                            'F31.9',  true),
('Schizophrenia',                               'F20.9',  true),
('Post-Traumatic Stress Disorder',              'F43.1',  true),
('Obsessive Compulsive Disorder',               'F42.9',  true),
('Panic Disorder',                              'F41.0',  true),
('Insomnia',                                    'G47.0',  true),
('Sleep Apnea',                                 'G47.3',  true),
('Migraine',                                    'G43.9',  true),
('Tension Headache',                            'G44.2',  true),
('Vertigo',                                     'H81.1',  true),
('Cataracts',                                   'H26.9',  true),
('Glaucoma',                                    'H40.9',  true),
('Macular Degeneration',                        'H35.3',  true),
('Diabetic Retinopathy',                        'H36',    true),
('Hearing Loss',                                'H91.9',  true),
('Otitis Media',                                'H66.9',  true),
('Sinusitis',                                   'J32.9',  true),
('Tonsillitis',                                 'J35.0',  true),
('Bronchitis',                                  'J40',    true),
('Tuberculosis',                                'A15.9',  true),
('COVID-19',                                    'U07.1',  true),
('Influenza',                                   'J11.1',  true),
('Sepsis',                                      'A41.9',  true),
('Cellulitis',                                  'L03.9',  true),
('Psoriasis',                                   'L40.9',  true),
('Eczema',                                      'L30.9',  true),
('Acne',                                        'L70.0',  true),
('Pressure Ulcer',                              'L89.9',  true),
('Obesity',                                     'E66.9',  true),
('Malnutrition',                                'E46',    true),
('Hyperlipidemia',                              'E78.5',  true),
('Metabolic Syndrome',                          'E88.81', true),
('Hyperkalemia',                                'E87.5',  true),
('Hyponatremia',                                'E87.1',  true),
('Dehydration',                                 'E86.0',  true),
('Fracture - Hip',                              'S72.9',  true),
('Fracture - Vertebral',                        'S22.9',  true),
('Fracture - Wrist',                            'S62.9',  true),
('Fall Injury',                                 'W19',    true),
('Benign Prostatic Hyperplasia',                'N40.0',  true),
('Kidney Stones',                               'N20.0',  true),
('Polycystic Ovary Syndrome',                   'E28.2',  true),
('Endometriosis',                               'N80.9',  true),
('Erectile Dysfunction',                        'N52.9',  true),
('Peripheral Artery Disease',                   'I73.9',  true),
('Varicose Veins',                              'I83.9',  true),
('Aortic Stenosis',                             'I35.0',  true),
('Myocardial Infarction',                       'I21.9',  true),
('Cardiac Arrest',                              'I46.9',  true);
