-- =====================================================
-- VITAL TABLE VERIFICATION SCRIPT
-- Checks if all 22 vital metric fields exist in vital table
-- =====================================================

-- Check table structure
DESCRIBE vital;

-- Count total columns in vital table
SELECT COUNT(*) as total_columns 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' 
AND TABLE_SCHEMA = DATABASE();

-- List all vital-related columns
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_COMMENT
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' 
AND TABLE_SCHEMA = DATABASE()
ORDER BY ORDINAL_POSITION;

-- Check if specific vital columns exist
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END as status,
    'height' as column_name
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'height'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'weight'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'weight'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'bmi'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'bmi'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'body_fat_percentage'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'body_fat_percentage'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'body_fat_mass'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'body_fat_mass'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'skeletal_muscle_percentage'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'skeletal_muscle_percentage'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'body_water_percentage'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'body_water_percentage'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'total_moisture'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'total_moisture'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'extracellular_water_pct'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'extracellular_water_pct'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'intracellular_water_pct'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'intracellular_water_pct'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'basal_metabolism'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'basal_metabolism'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'visceral_fat_level'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'visceral_fat_level'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'protein'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'protein'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'mineral'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'mineral'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'body_age'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'body_age'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'overall'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'overall'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'temperature'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'temperature'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'bp_heart_rate'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'bp_heart_rate'
UNION ALL
SELECT 
    CASE WHEN COUNT(*) > 0 THEN 'EXISTS' ELSE 'MISSING' END,
    'spo2_heart_rate'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'vital' AND COLUMN_NAME = 'spo2_heart_rate';

-- Check indexes
SHOW INDEX FROM vital;